// ============================================================
// Daily Win — Default Motivational Quotes (German)
// 60 short, warm, non-cringe quotes for daily rotation.
// ============================================================

export const DEFAULT_QUOTES: string[] = [
  'Jeder kleine Schritt zählt.',
  'Du bist weiter, als du denkst.',
  'Fortschritt beginnt mit dem Anfangen.',
  'Sei stolz auf das, was du heute geschafft hast.',
  'Auch kleine Siege verdienen Anerkennung.',
  'Dein Weg ist einzigartig — vergleiche dich nicht.',
  'Heute ist ein guter Tag, um gut zu dir zu sein.',
  'Wachstum passiert oft leise.',
  'Du darfst auch mal langsam machen.',
  'Jeder Tag bringt eine neue Chance.',
  'Dankbarkeit verändert den Blick auf alles.',
  'Mut bedeutet, trotzdem weiterzumachen.',
  'Du bist genug — genau so, wie du bist.',
  'Kleine Gewohnheiten bauen große Veränderungen.',
  'Erlaube dir, stolz auf dich zu sein.',
  'Das Beste, was du tun kannst, ist anfangen.',
  'Dein Tempo ist genau richtig.',
  'Heute darfst du einfach da sein.',
  'Vertraue dem Prozess.',
  'Jeder Moment der Ruhe ist wertvoll.',
  'Du machst das gut — auch wenn es sich nicht so anfühlt.',
  'Fortschritt ist nicht immer sichtbar, aber immer real.',
  'Sei geduldig mit dir selbst.',
  'Was du heute pflanzt, wächst morgen.',
  'Du hast schon so viel geschafft.',
  'Ein Atemzug genügt, um neu anzufangen.',
  'Dein Einsatz wird sich auszahlen.',
  'Es ist okay, nicht perfekt zu sein.',
  'Heute ist ein Tag voller Möglichkeiten.',
  'Du verdienst es, gut zu dir zu sein.',
  'Stärke zeigt sich auch im Innehalten.',
  'Jede gute Entscheidung ist ein Gewinn.',
  'Du bist auf dem richtigen Weg.',
  'Dankbarkeit macht reich — ganz ohne Geld.',
  'Erlaube dir, Hilfe anzunehmen.',
  'Der beste Zeitpunkt ist jetzt.',
  'Du bist stärker, als du glaubst.',
  'Fehler sind Lehrer, keine Feinde.',
  'Freude liegt oft in den kleinen Dingen.',
  'Du darfst Pausen machen — das ist kein Aufgeben.',
  'Morgen ist ein neuer Anfang.',
  'Vertraue dir selbst.',
  'Das Leben belohnt die, die dranbleiben.',
  'Jeder Schritt vorwärts zählt.',
  'Du hast heute die Wahl, gut zu dir zu sein.',
  'Wertschätze, was da ist.',
  'Deine Reise hat ihren eigenen Rhythmus.',
  'Manchmal ist gut genug — perfekt.',
  'Du wirst das schaffen.',
  'Lass los, was du nicht ändern kannst.',
  'Heute darfst du stolz auf dich sein.',
  'Kleine Freuden sind große Geschenke.',
  'Gib dir die Liebe, die du anderen gibst.',
  'Deine Zeit kommt — bleib dran.',
  'Atme tief ein. Du bist hier.',
  'Fortschritt braucht keine Perfektion.',
  'Jeder Tag ist ein neues Kapitel.',
  'Du machst einen Unterschied.',
  'Glaube an das, was noch kommt.',
  'Heute ist dein Tag.',
];
